---
language: node_js
node_js:
  - 10.19
notifications:
  - viniciusseus@gmail.com

before_install:
  - npm install -g bower@1.8.8
  - npm install -g grunt-cli@0.1.13
  - npm install -g karma@6.2
  - npm install -g karma-jasmine@4.0
  - npm install -g protractor@7.0
  - npm install -g karma-phantomjs-launcher
  - webdriver-manager update
  - bower install

before_script:
  - grunt
  - cd dist

script:
  - karma start config/karma.config.js --single-run --browsers PhantomJS
