---
language: node_js
node_js:
  - 10.19
notifications:
  - viniciusseus@gmail.com

services:
  - mongodb
env:
  global:
    - NODE_ENV: test

addons:
  sauce_connect: true

before_install:
  - npm install -g bower@1.8.8
  - npm install -g grunt-cli@0.1.13
  - npm install -g karma@6.2
  - npm install -g karma-jasmine@4.0
  - npm install -g protractor@7.0
  - npm install -g karma-phantomjs-launcher
  - webdriver-manager update
  - bower install

before_script:
  - node test/data.js
  - grunt
  - cd dist

script:
  - node server &
  - protractor config/protractor.js
